on:
  workflow_call:
    inputs:
      username:
        description: 'Username'
        default: 'World'
        required: false
        type: string
    secrets:
      secretin:
        required: false
        
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Print username
        env:
          SECRET: ${{ secrets.TEST }}
        run: |
          echo "Hello ${{ inputs.username }}"
          echo "Secret in ${{ secrets.secretin }}"
          echo "Can I hase secret from repo? $SECRET"
